apiVersion: v1
kind: Pod
metadata:
  name: apache-basic-auth-pod
  namespace: ns-sub-apache-pezhang
  labels:
    app: apache-basic-auth
spec:
  subdomain: chart-web
  containers:
  - name: apache-basic-auth
    image: quay.io/pezhang/apache-basic-auth-new:latest
    ports:
    - containerPort: 8080
