apiVersion: v1
kind: Service
metadata:
  name: apache-basic-auth-service
  labels:
    app: apache-basic-auth
spec:
  selector:
    app: apache-basic-auth
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
